name = "OptimizationBenchmarkProblems"
uuid = "94c702ba-c5d1-427f-af34-2074e518882b"
authors = ["kurodamaria <xfreunion@gmail.com> and contributors"]
version = "1.0.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
